; Loaded via PHP_INI_SCAN_DIR when starting the app server.
upload_max_filesize = 12M
post_max_size = 1200M
max_file_uploads = 120
memory_limit = 1024M
max_execution_time = 600
max_input_time = 600
max_input_vars = 5000
